#cloud-config
apt:
  sources:
    docker:
      source: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable"
      keyid: 0EBFCD88
packages:
  - [docker-ce, 17.03.2~ce-0~ubuntu-xenial]
runcmd:
  - usermod -G docker -a ubuntu
