#cloud-config
rancher:
  resize_device: /dev/nvme0n1
  services:
    rancher-server:
      image: rancher/server:${rancher_version}
      ports:
        - 80:80
        - 443:443
      restart: unless-stopped
      command: --acme-domain ${server_name}

